:chore memo

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -18,13 +18,13 @@ fi
 ############################################################
 # if .zshrc exists → backup
 
-function zsh_confing {
+function zsh_config {
 	if [ -f "$HOME/.zshrc" ]; then
 		BACKUP="$HOME/.zshrc_$(date +"%Y%m%d_%H%M%S")"
-		cp -r "$HOME/.zshrc" "$BACKUP" || { echo ".zshrc backup faild"; exit 1; }
+		cp -r "$HOME/.zshrc" "$BACKUP" || { echo ".zshrc backup failed"; exit 1; }
 		echo ".zshrc backup done"
 	else
-		ln -s "$DOT_DIR/.config/.zshrc" "$HOME/.zshrc" || { echo ".zshrc link faild"; exit 1; }
+		ln -s "$DOT_DIR/.config/.zshrc" "$HOME/.zshrc" || { echo ".zshrc link failed"; exit 1; }
 		echo ".zshrc linked"
 	fi
 }
@@ -34,20 +34,20 @@ function zsh_confing {
 function tmux_config {
 	if [ -f "$HOME/.tmux.conf" ]; then
 		BACKUP="$HOME/.tmux.conf_$(date +"%Y%m%d_%H%M%S")"
-		cp -r "$HOME/.tmux.conf" "$BACKUP" || { echo "tmux backup faild"; exit 1; }
+		cp -r "$HOME/.tmux.conf" "$BACKUP" || { echo "tmux backup failed"; exit 1; }
 		echo ".tmux.conf backup done"
 	else
-		ln -sfn "$DOT_DIR/.config/.tmux.conf" "$HOME/.tmux.conf" || { echo "tmux link faild"; exit 1; }
+		ln -sfn "$DOT_DIR/.config/.tmux.conf" "$HOME/.tmux.conf" || { echo "tmux link failed"; exit 1; }
 		echo ".tmux.conf linked"
 	fi
 
 	# tmux alias
 	if [ -f "$HOME/.tmux.session.conf" ]; then
 		BACKUP="$HOME/.tmux.session.conf_$(date +"%Y%m%d_%H%M%S")"
-		cp -r "$HOME/.tmux.session.conf" "$BACKUP" || { echo "tmux session backup faild"; exit 1; }
+		cp -r "$HOME/.tmux.session.conf" "$BACKUP" || { echo "tmux session backup failed"; exit 1; }
 		echo "tmux session backup done"
 	else
-		ln -s "$DOT_DIR/.config/.tmux.session.conf" "$HOME/.tmux.session.conf" || { echo "tmux session link faild"; exit 1; }
+		ln -s "$DOT_DIR/.config/.tmux.session.conf" "$HOME/.tmux.session.conf" || { echo "tmux session link failed"; exit 1; }
 		echo "tmux session linked"
 	fi
 }
@@ -62,11 +62,11 @@ function wezterm_config {
 
 	if [ -d "$WEZTERM_DIR" ]; then
 		BACKUP_DIR="$HOME/.config/wezterm_backup"
-		cp -r "$WEZTERM_DIR" "$BACKUP_DIR" || { echo ".wezterm backup faild"; exit 1; }
+		cp -r "$WEZTERM_DIR" "$BACKUP_DIR" || { echo ".wezterm backup failed"; exit 1; }
 		echo "wezterm config backup done"
 	else
 		# mkdir -p "$WEZTERM_DIR"
-		ln -s "$WEZ_TARGET_DIR"/ "$HOME/.config/" || { echo ".wezterm link faild"; exit 1; }
+		ln -s "$WEZ_TARGET_DIR"/ "$HOME/.config/" || { echo ".wezterm link failed"; exit 1; }
 		echo "wezterm linked"
 	fi
 }
@@ -80,10 +80,10 @@ function lazygit_config {
 
 	if [ -f "$LAZY_TARGET_DIR/config.yml" ]; then
 		BACKUP_FILE="$LAZY_TARGET_DIR/config.$(date +"%Y%m%d_%H%M%S").yml"
-		cp -r "$LAZY_TARGET_DIR/config.yml" "$BACKUP_FILE" || { echo "lazygit backup faild"; exit 1; }
+		cp -r "$LAZY_TARGET_DIR/config.yml" "$BACKUP_FILE" || { echo "lazygit backup failed"; exit 1; }
 		echo "lazygit config backuped"
 	else
-		ln -s "$LAGY_CONFIG" "$LAZY_TARGET_DIR/config.yml" || { echo "lazygit link faild"; exit 1; }
+		ln -s "$LAGY_CONFIG" "$LAZY_TARGET_DIR/config.yml" || { echo "lazygit link failed"; exit 1; }
 		echo "lazygit config linked"
 	fi
 }
@@ -98,22 +98,22 @@ function vim_config {
 	# neovim link
 	if [ -d "$NVIM_DIR/nvim" ]; then
 		BACKUP_DIR="$HOME/.config/nvim_backup_$(date +"%Y%m%d_%H%M%S")"
-		cp -r "$NVIM_DIR" "$BACKUP_DIR" || { echo "nvim backup faild"; exit 1; }
+		cp -r "$NVIM_DIR" "$BACKUP_DIR" || { echo "nvim backup failed"; exit 1; }
 		echo "nvim backup done"
 	else
 		mkdir -p "$NVIM_DIR"
-		ln -s "$NVIM_TARGET_DIR" "$NVIM_DIR" || { echo "nvim link faild"; exit 1; }
+		ln -s "$NVIM_TARGET_DIR" "$NVIM_DIR" || { echo "nvim link failed"; exit 1; }
 		echo "nvim linked"
 	fi
 
 	# vim link
 	if [ -f "$HOME/.vimrc" ]; then
 		BACKUP_FILE="$HOME/.vimrc_backup_$(date +"%Y%m%d_%H%M%S")"
-		cp -r "$HOME/.vimrc" "$BACKUP_FILE" || { echo "vim backup faild"; exit 1; }
+		cp -r "$HOME/.vimrc" "$BACKUP_FILE" || { echo "vim backup failed"; exit 1; }
 		echo ".vimrc backup done"
 	else
 		echo "$DOT_DIR/.vimrc to $HOME/.vimrc"
-		ln -s "$DOT_DIR/.vimrc" "$HOME/.vimrc" || { echo "vim link faild"; exit 1; }
+		ln -s "$DOT_DIR/.vimrc" "$HOME/.vimrc" || { echo "vim link failed"; exit 1; }
 		echo ".vimrc linked"
 	fi
 }
@@ -123,7 +123,7 @@ function vim_config {
 
 function setup() {
 	if [[ ! -f "$HOME/commands/setup" ]]; then
-		ln -s "$DOT_DIR/setup" "$HOME/commands/setup" || { echo "setup.sh link faild"; exit 1; }
+		ln -s "$DOT_DIR/setup" "$HOME/commands/setup" || { echo "setup.sh link failed"; exit 1; }
 		echo "setup linked"
 	else
 		echo "setup already linked"
@@ -161,7 +161,7 @@ while getopts ":lzstwvh" optKey; do
 			;;
 		z)
 			echo "load zsh config"
-			zsh_confing
+			zsh_config
 			;;
 		w)
 			echo "load wezterm config"
@@ -188,4 +188,3 @@ done
 ############################################################
 
 # end of script
-
