save

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -61,8 +61,8 @@ function wezterm_config {
 	WEZTERM_DIR="$HOME/.config/wezterm"
 
 	if [ -d "$WEZTERM_DIR" ]; then
-		BACKUP_DIR="$HOME/.config/wezterm_backup_$(date +"%Y%m%d_%H%M%S")"
-		cp -r "$WEZTERM_DIR"/* "$BACKUP_DIR" || { echo ".wezterm backup faild"; exit 1; }
+		BACKUP_DIR="$HOME/.config/wezterm_backup"
+		cp -r "$WEZTERM_DIR" "$BACKUP_DIR" || { echo ".wezterm backup faild"; exit 1; }
 		echo "wezterm config backup done"
 	else
 		# mkdir -p "$WEZTERM_DIR"
